/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as CancellationPolicyRouteImport } from './routes/cancellation-policy'
import { Route as CancelBookingRouteImport } from './routes/cancel-booking'
import { Route as BookingSuccessRouteImport } from './routes/booking-success'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RutasSlugRouteImport } from './routes/rutas.$slug'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const CancellationPolicyRoute = CancellationPolicyRouteImport.update({
  id: '/cancellation-policy',
  path: '/cancellation-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const CancelBookingRoute = CancelBookingRouteImport.update({
  id: '/cancel-booking',
  path: '/cancel-booking',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingSuccessRoute = BookingSuccessRouteImport.update({
  id: '/booking-success',
  path: '/booking-success',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RutasSlugRoute = RutasSlugRouteImport.update({
  id: '/rutas/$slug',
  path: '/rutas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/booking-success': typeof BookingSuccessRoute
  '/cancel-booking': typeof CancelBookingRoute
  '/cancellation-policy': typeof CancellationPolicyRoute
  '/cookies': typeof CookiesRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/rutas/$slug': typeof RutasSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/booking-success': typeof BookingSuccessRoute
  '/cancel-booking': typeof CancelBookingRoute
  '/cancellation-policy': typeof CancellationPolicyRoute
  '/cookies': typeof CookiesRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/rutas/$slug': typeof RutasSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/booking-success': typeof BookingSuccessRoute
  '/cancel-booking': typeof CancelBookingRoute
  '/cancellation-policy': typeof CancellationPolicyRoute
  '/cookies': typeof CookiesRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/rutas/$slug': typeof RutasSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/booking-success'
    | '/cancel-booking'
    | '/cancellation-policy'
    | '/cookies'
    | '/privacy'
    | '/terms'
    | '/rutas/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/booking-success'
    | '/cancel-booking'
    | '/cancellation-policy'
    | '/cookies'
    | '/privacy'
    | '/terms'
    | '/rutas/$slug'
  id:
    | '__root__'
    | '/'
    | '/booking-success'
    | '/cancel-booking'
    | '/cancellation-policy'
    | '/cookies'
    | '/privacy'
    | '/terms'
    | '/rutas/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingSuccessRoute: typeof BookingSuccessRoute
  CancelBookingRoute: typeof CancelBookingRoute
  CancellationPolicyRoute: typeof CancellationPolicyRoute
  CookiesRoute: typeof CookiesRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  RutasSlugRoute: typeof RutasSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancellation-policy': {
      id: '/cancellation-policy'
      path: '/cancellation-policy'
      fullPath: '/cancellation-policy'
      preLoaderRoute: typeof CancellationPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancel-booking': {
      id: '/cancel-booking'
      path: '/cancel-booking'
      fullPath: '/cancel-booking'
      preLoaderRoute: typeof CancelBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-success': {
      id: '/booking-success'
      path: '/booking-success'
      fullPath: '/booking-success'
      preLoaderRoute: typeof BookingSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rutas/$slug': {
      id: '/rutas/$slug'
      path: '/rutas/$slug'
      fullPath: '/rutas/$slug'
      preLoaderRoute: typeof RutasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingSuccessRoute: BookingSuccessRoute,
  CancelBookingRoute: CancelBookingRoute,
  CancellationPolicyRoute: CancellationPolicyRoute,
  CookiesRoute: CookiesRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  RutasSlugRoute: RutasSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
