/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookingSuccessRouteImport } from './routes/booking-success'
import { Route as CancelBookingRouteImport } from './routes/cancel-booking'
import { Route as CancellationPolicyRouteImport } from './routes/cancellation-policy'
import { Route as CondicionesRouteImport } from './routes/condiciones'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ManageBookingRouteImport } from './routes/manage-booking'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as GuiasIndexRouteImport } from './routes/guias.index'
import { Route as GuiasSlugRouteImport } from './routes/guias.$slug'
import { Route as RutasSlugRouteImport } from './routes/rutas.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingSuccessRoute = BookingSuccessRouteImport.update({
  id: '/booking-success',
  path: '/booking-success',
  getParentRoute: () => rootRouteImport,
} as any)
const CancelBookingRoute = CancelBookingRouteImport.update({
  id: '/cancel-booking',
  path: '/cancel-booking',
  getParentRoute: () => rootRouteImport,
} as any)
const CancellationPolicyRoute = CancellationPolicyRouteImport.update({
  id: '/cancellation-policy',
  path: '/cancellation-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const CondicionesRoute = CondicionesRouteImport.update({
  id: '/condiciones',
  path: '/condiciones',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageBookingRoute = ManageBookingRouteImport.update({
  id: '/manage-booking',
  path: '/manage-booking',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiasIndexRoute = GuiasIndexRouteImport.update({
  id: '/guias/',
  path: '/guias/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiasSlugRoute = GuiasSlugRouteImport.update({
  id: '/guias/$slug',
  path: '/guias/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RutasSlugRoute = RutasSlugRouteImport.update({
  id: '/rutas/$slug',
  path: '/rutas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/booking-success': typeof BookingSuccessRoute
  '/cancel-booking': typeof CancelBookingRoute
  '/cancellation-policy': typeof CancellationPolicyRoute
  '/condiciones': typeof CondicionesRoute
  '/cookies': typeof CookiesRoute
  '/manage-booking': typeof ManageBookingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/guias/$slug': typeof GuiasSlugRoute
  '/rutas/$slug': typeof RutasSlugRoute
  '/guias/': typeof GuiasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/booking-success': typeof BookingSuccessRoute
  '/cancel-booking': typeof CancelBookingRoute
  '/cancellation-policy': typeof CancellationPolicyRoute
  '/condiciones': typeof CondicionesRoute
  '/cookies': typeof CookiesRoute
  '/manage-booking': typeof ManageBookingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/guias/$slug': typeof GuiasSlugRoute
  '/rutas/$slug': typeof RutasSlugRoute
  '/guias': typeof GuiasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/booking-success': typeof BookingSuccessRoute
  '/cancel-booking': typeof CancelBookingRoute
  '/cancellation-policy': typeof CancellationPolicyRoute
  '/condiciones': typeof CondicionesRoute
  '/cookies': typeof CookiesRoute
  '/manage-booking': typeof ManageBookingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/guias/$slug': typeof GuiasSlugRoute
  '/rutas/$slug': typeof RutasSlugRoute
  '/guias/': typeof GuiasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/booking-success'
    | '/cancel-booking'
    | '/cancellation-policy'
    | '/condiciones'
    | '/cookies'
    | '/manage-booking'
    | '/privacy'
    | '/terms'
    | '/guias/$slug'
    | '/rutas/$slug'
    | '/guias/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/booking-success'
    | '/cancel-booking'
    | '/cancellation-policy'
    | '/condiciones'
    | '/cookies'
    | '/manage-booking'
    | '/privacy'
    | '/terms'
    | '/guias/$slug'
    | '/rutas/$slug'
    | '/guias'
  id:
    | '__root__'
    | '/'
    | '/booking-success'
    | '/cancel-booking'
    | '/cancellation-policy'
    | '/condiciones'
    | '/cookies'
    | '/manage-booking'
    | '/privacy'
    | '/terms'
    | '/guias/$slug'
    | '/rutas/$slug'
    | '/guias/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingSuccessRoute: typeof BookingSuccessRoute
  CancelBookingRoute: typeof CancelBookingRoute
  CancellationPolicyRoute: typeof CancellationPolicyRoute
  CondicionesRoute: typeof CondicionesRoute
  CookiesRoute: typeof CookiesRoute
  ManageBookingRoute: typeof ManageBookingRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  GuiasSlugRoute: typeof GuiasSlugRoute
  RutasSlugRoute: typeof RutasSlugRoute
  GuiasIndexRoute: typeof GuiasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-success': {
      id: '/booking-success'
      path: '/booking-success'
      fullPath: '/booking-success'
      preLoaderRoute: typeof BookingSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancel-booking': {
      id: '/cancel-booking'
      path: '/cancel-booking'
      fullPath: '/cancel-booking'
      preLoaderRoute: typeof CancelBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancellation-policy': {
      id: '/cancellation-policy'
      path: '/cancellation-policy'
      fullPath: '/cancellation-policy'
      preLoaderRoute: typeof CancellationPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/condiciones': {
      id: '/condiciones'
      path: '/condiciones'
      fullPath: '/condiciones'
      preLoaderRoute: typeof CondicionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage-booking': {
      id: '/manage-booking'
      path: '/manage-booking'
      fullPath: '/manage-booking'
      preLoaderRoute: typeof ManageBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guias/': {
      id: '/guias/'
      path: '/guias'
      fullPath: '/guias/'
      preLoaderRoute: typeof GuiasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guias/$slug': {
      id: '/guias/$slug'
      path: '/guias/$slug'
      fullPath: '/guias/$slug'
      preLoaderRoute: typeof GuiasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rutas/$slug': {
      id: '/rutas/$slug'
      path: '/rutas/$slug'
      fullPath: '/rutas/$slug'
      preLoaderRoute: typeof RutasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingSuccessRoute: BookingSuccessRoute,
  CancelBookingRoute: CancelBookingRoute,
  CancellationPolicyRoute: CancellationPolicyRoute,
  CondicionesRoute: CondicionesRoute,
  CookiesRoute: CookiesRoute,
  ManageBookingRoute: ManageBookingRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  GuiasSlugRoute: GuiasSlugRoute,
  RutasSlugRoute: RutasSlugRoute,
  GuiasIndexRoute: GuiasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
